-- 12. Insert a record to represent Mary Smith renting the movie ACADEMY
-- DINOSAUR from Mike Hillyer at store number 1 today. Then write a query to
-- capture the exact row you entered into the rental table.
-- (Note: Your rental date value will show the date and time you entered the
-- record, not 2021.)